pages/urls.py
from django.urls import path

from .views import PageDetailView

app_name = "pages"

urlpatterns = [
    path("", PageDetailView.as_view(), name="home"),
    path("<slug:slug>/", PageDetailView.as_view(), name="page_detail"),
]

site_service/urls.py
from django.conf import settings
from django.conf.urls.i18n import i18n_patterns
from django.conf.urls.static import static
from django.contrib import admin
from django.contrib.sitemaps.views import sitemap
from django.urls import path
from django.urls.conf import include
from django.views.generic import TemplateView

from core.enums import Environment
from core.sitemaps import PageSitemap, HomepageSitemap

sitemaps = {
    "home": HomepageSitemap,
    "pages": PageSitemap,
}

urlpatterns = [
    path("admin/", admin.site.urls),
    path("rosetta/", include("rosetta.urls")),
    path(
        "robots.txt", TemplateView.as_view(
            template_name="robots.txt", content_type="text/plain"
        )
    ),
    path(
        "sitemap.xml", sitemap, {"sitemaps": sitemaps},
        name="django.contrib.sitemaps.views.sitemap"
    ),
    path("ckeditor5/", include("django_ckeditor_5.urls")),
]

urlpatterns += i18n_patterns(
    path("", include("pages.urls", namespace="pages")),
    prefix_default_language=False
)

if settings.DEBUG:
    urlpatterns += static(
        settings.MEDIA_URL, document_root=settings.MEDIA_ROOT
    )

if settings.ENVIRONMENT == Environment.DEV.value:
    urlpatterns += [
        path("__reload__/", include("django_browser_reload.urls")),
    ]

templates/inferno/includes/footer.html
{% load i18n static menu_tags %}

<div class="container py-5 text-center">
  {% get_menu "Footer Menu" as MENU %}
  {% if MENU.items %}
    {% include "includes/menu/footer_menu.html" with menu=MENU %}
  {% endif %}
  <p class="opacity-50 d-inline">
    &copy; {% now "Y" %} {{ site_options.brand_name }}. {% translate "All rights reserved" %}.</p>
</div>

templates/inferno/includes/header.html
{% load i18n menu_tags %}

<nav class="navbar navbar-expand-xl p-0">
  <div class="container justify-content-center">
    <a class="navbar-brand" href="{% url 'pages:home' %}">
      {% if site_options.sponsor_logo %}
        <img
          src="{{ site_options.sponsor_logo }}"
          alt="{{ header_image.default_alt_text }}"
          width="160" loading="lazy">
      {% else %}
        <div class="py-3">{{ site_options.brand_name }}</div>
      {% endif %}
    </a>

    <button class="navbar-toggler border-0 shadow-none" type="button" data-bs-toggle="collapse"
            data-bs-target="#navbarNav"
            aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
      <span></span>
    </button>


    {% include "includes/language_switcher.html" %}
  </div>
</nav>

templates/inferno/includes/partners.html
{% load i18n %}
<div class="aside-list list-group mb-5">
  {% for partner in partners %}
    <a href="{{ partner.url }}"
       class="list-group-item list-group-item-action text-break d-flex justify-content-between"
       target="_blank"
    >
      {{ partner.name }}

      <svg class="icon">
        <use xlink:href="#arrow-right-long-line"></use>
      </svg>
    </a>
  {% endfor %}
</div>